"""End-to-end CLI tests + golden reports for the three demo PRs.

Demo SHAs are deterministic, so the reports are byte-stable. To accept intended
output changes: UPDATE_GOLDEN=1 pytest tests/test_report.py
"""
import json
import os
import sys
from pathlib import Path

import pytest

from blastradius.cli import main

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "demo"))
import seed_demo  # noqa: E402

GOLDEN = Path(__file__).parent / "golden"
BRANCHES = {"pr1": "pr1/pagination-fix", "pr2": "pr2/refund-status", "pr3": "pr3/discount-tier"}


@pytest.fixture(scope="module")
def demo_repo(tmp_path_factory):
    repo = tmp_path_factory.mktemp("demo")
    seed_demo.seed(repo, force=True)
    return repo


def _run(repo, branch, tmp_path, *extra):
    out = tmp_path / "report.out"
    code = main(["--repo", str(repo), "--diff", f"main...{branch}", "--no-llm", "--out", str(out), *extra])
    return code, out.read_text(encoding="utf-8")


@pytest.mark.parametrize("name", BRANCHES)
def test_golden(demo_repo, tmp_path, name):
    code, report = _run(demo_repo, BRANCHES[name], tmp_path)
    assert code == 0
    golden = GOLDEN / f"{name}.md"
    if os.environ.get("UPDATE_GOLDEN"):
        golden.write_text(report, encoding="utf-8", newline="\n")
    assert report == golden.read_text(encoding="utf-8"), f"report changed; rerun with UPDATE_GOLDEN=1 if intended"


def test_report_has_no_machine_specific_content(demo_repo, tmp_path):
    _, report = _run(demo_repo, BRANCHES["pr2"], tmp_path)
    assert str(demo_repo) not in report and str(tmp_path) not in report


def test_json_output(demo_repo, tmp_path):
    code, report = _run(demo_repo, BRANCHES["pr3"], tmp_path, "--format", "json")
    data = json.loads(report)
    assert code == 0
    assert data["runbook"]["source"] == "template"
    assert {c["file"] for c in data["blast"]["callers"]} >= {"app/api/checkout.py", "tests/test_pricing.py"}
    assert data["checklist"][0]["severity"] == "high"


@pytest.mark.parametrize("name,threshold,expected", [
    ("pr1", "high", 0), ("pr1", "low", 1),
    ("pr3", "high", 1), ("pr2", "med", 1),
])
def test_fail_on(demo_repo, tmp_path, name, threshold, expected):
    code, _ = _run(demo_repo, BRANCHES[name], tmp_path, "--fail-on", threshold)
    assert code == expected


def test_bad_range_exits_2(demo_repo, capsys):
    assert main(["--repo", str(demo_repo), "--diff", "main...no-such-branch", "--no-llm"]) == 2
    assert "error:" in capsys.readouterr().err


def test_missing_bob_config_falls_back(demo_repo, tmp_path, monkeypatch, capsys):
    monkeypatch.delenv("BOB_API_URL", raising=False)
    monkeypatch.delenv("BOB_API_KEY", raising=False)
    out = tmp_path / "r.md"
    assert main(["--repo", str(demo_repo), "--diff", "main...pr1/pagination-fix", "--out", str(out)]) == 0
    assert "falling back to template" in capsys.readouterr().err
    assert "_Generated by: template_" in out.read_text(encoding="utf-8")
